channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.7.5

  - pip=20.1
  - pip:
      # Define pip packages here.
      # https://pypi.org/
      #- rpaframework==12.6.1 # https://rpaframework.org/releasenotes.html
      - https://github.com/mikahanninen/robots/blob/main/builds/rpaframework-12.7.0.a4f2b4e0-py3-none-any.whl?raw=true
